#Dies ist die Standert Config
AmountOnKill: 10 #Wie viel man durch das Töten von Spielern bekommnt
StartAmount: 20 #Wie viel man am Anfang hat
PublicDeathMessage: false #Ob man einen Globale Todes Nachricht haben möchte
# %kill% -> von dem Killer der Name %spieler% -> von dem Getöteten Spieler der Name
DeathMessage: "&c%killer% &4hatt &c%spieler% &4getötet" #Die Todes nachricht

#Kits

Kit:
  Start: # <-- Kit Namen
    DisplayName: '&eStart-Kit' #<-- DisplayNamen // Wie das Kit im Kit Inventar oder im ShopInventar angezeit Wird
    Cost: 1 #<-- Wie Viel das Kit Kostet
    Icon: LEATHER_BOOTS # // Wie das Kit im Kit Inventar oder im ShopInventar angezeit Wird
    Items: 
      '1': #<-- Der Kit Name (Muss eine Zahl Sein)
      - IRON_SWORD #<-- Das item muss in einem Kompatibelen Format sein
      - '&eStart-Schwert' #<-- Der Name in einem Color Code
      - '1' #<-- Der Betrag von dem Item
      - '0' #<-- Die Meta daten
      - '16' #<-- Die Enchantment ID
      - '1' #<-- Das Enchantment LvL
      - '&eSchwert des Todes!' #<-- Lore des Item
    ItemList: #<-- Kit Liste, hier müssen alle oben eingetragenen Kits eingetragen werden
    - 1 #<-- Kit '1'
KitList: #<-- Hier Müssen alle Kits eingetragen werden die Erstellt worden sind
- Start #<-- Kit: Start

# Wenn ihr jetzt ein Zweites Kit item Erstellen Möchte:
Kit:
  Start:
    DisplayName: '&eStart-Kit'
    Cost: 1
    Icon: LEATHER_BOOTS
    Items:
      '1':
      - IRON_SWORD
      - '&eStart-Schwert'
      - '1'
      - '0'
      - '16'
      - '1'
      - '&eSchwert des Todes!'
      '2': #<-- Zweites Kit in einem String format
      - APPLE
      - '&cApfel'
      - '10'
      - '0'
      - '0'
      - '0'
      - '&cApfel Kuchen'
      '3':
      - DIAMOND
      - '&cJumper' #<-- Funktions Namen
      - '1'
      - '0'
      - '0'
      - '0'
      - '&1Jumper'
    ItemList: #Alle eingetragenen Kits
    - 1
    - 2
    - 3
# Funktions Namen
# Blitze Schleudern: &cHammer von Thor
# Spieler in einem Radius von 5 Blöcken anzünden: &cFeuer
# Jumper Funktion: &cJumper

#Enchantment Id's
#Armour

#0 | minecraft:protection | Protection
#1 | minecraft:fire_protection | Fire Protection
#2 | minecraft:feather_falling | Feather Falling
#3 | minecraft:blast_protection | Blast Protection
#4 | minecraft:projectile_protection | Projectile Protection
#5 | minecraft:respiration | Respiration
#6 | minecraft:aqua_affinity | Aqua Affinity
#7 | minecraft:thorns | Thorns
#8 | minecraft:depth_strider | Depth Strider (1.8)
#9 | minecraft:frost_walker | Frost Walker (1.9)

#Weapons

#16 | minecraft:sharpness | Sharpness
#17 | minecraft:smite | Smite
#18 | minecraft:bane_of_arthropods | Bane Of Arthropods
#19 | minecraft:knockback | Knockback
#20 | minecraft:fire_aspect | Fire Aspect
#21 | minecraft:looting | Looting

#Tools

#32 | minecraft:efficiency | Efficiency
#33 | minecraft:silk_touch | Silk Touch
#35 | minecraft:fortune | Fortune

#Bows

#48 | minecraft:power | Power
#49 | minecraft:punch | Punch
#50 | minecraft:flame | Flame
#51 | minecraft:infinity | Infinity

#Fishing Rods

#61 | minecraft:luck_of_the_sea | Luck of the Sea (1.8)
#62 | minecraft:lure | Lure (1.8)

#Everything

#34 | minecraft:unbreaking | Unbreaking
#70 | minecraft:mending | Mending (1.9)
